# base
FROM node:10.15.3 as builder

RUN mkdir /usr/app
RUN mkdir /usr/app/client
WORKDIR /usr/app/client

ENV PATH /usr/app/client/node_modules/.bin:$PATH
ENV NODE_ENV production 

COPY ./package.json /usr/app/client/package.json
RUN yarn install --silent

COPY . /usr/app/client

RUN yarn build


# production environment
FROM nginx:1.14.0-alpine

COPY --from=builder /usr/app/client/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]