const customerCards = [
    {
      id: 1,
      title: 'My Account',
      description: 'Change your email, password, profile and preferences here.',
      link: '/customer/account',
      buttonName: 'Edit Account',
      icon: 'account_box',
    },
    {
      id: 2,
      title: 'My Participants',
      description: 'Add, remove, or update participants for NNMTA events.',
      link: '/customer/participants',
      buttonName: 'Edit Participants',
      icon: 'group_add',
    },
    {
      id: 3,
      title: 'Register for an Event',
      description: 'Register your participants for upcoming NNMTA events.',
      link: '/customer/register-for-an-event',
      buttonName: 'Register Now',
      icon: 'event_available',
    },
    {
      id: 4,
      title: 'My Enrollments',
      description: 'View all events you\'ve signed up for.',
      link: '/customer/my-enrollments',
      buttonName: 'View Enrollments',
      icon: 'event',
    },
    {
      id: 5,
      title: 'Events Calendar',
      description: 'View all upcoming events on our Google calendar.',
      link: '/customer/events-calendar',
      buttonName: 'View Calendar',
      icon: 'calendar_today',
    },
    {
      id: 6,
      title: 'Getting Started',
      description: 'Answers to commonly asked questions.',
      link: '/customer/faq',
      buttonName: 'FAQ',
      icon: 'help_outline',
    },
    {
      id: 7,
      title: 'About NNMTA',
      description: 'Learn about our organization\'s mission, history, and values.',
      link: '/customer/about',
      buttonName: 'Who We Are',
      icon: 'music_note',
    },
    {
      id: 8,
      title: 'Contact Us',
      description: 'Contact us here if you need help with something.',
      link: '/customer/contact-us',
      buttonName: 'Message Us',
      icon: 'contact_mail',
    },
  ];

  export default customerCards;
